# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/v1rushb/newDev/CryptoGraphix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/v1rushb/newDev/CryptoGraphix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/v1rushb/newDev/CryptoGraphix/CMakeFiles /home/v1rushb/newDev/CryptoGraphix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/v1rushb/newDev/CryptoGraphix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CryptoGraphix

# Build rule for target.
CryptoGraphix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CryptoGraphix
.PHONY : CryptoGraphix

# fast build rule for target.
CryptoGraphix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/build
.PHONY : CryptoGraphix/fast

src/AES256Encryption.o: src/AES256Encryption.cpp.o
.PHONY : src/AES256Encryption.o

# target to build an object file
src/AES256Encryption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/AES256Encryption.cpp.o
.PHONY : src/AES256Encryption.cpp.o

src/AES256Encryption.i: src/AES256Encryption.cpp.i
.PHONY : src/AES256Encryption.i

# target to preprocess a source file
src/AES256Encryption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/AES256Encryption.cpp.i
.PHONY : src/AES256Encryption.cpp.i

src/AES256Encryption.s: src/AES256Encryption.cpp.s
.PHONY : src/AES256Encryption.s

# target to generate assembly for a file
src/AES256Encryption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/AES256Encryption.cpp.s
.PHONY : src/AES256Encryption.cpp.s

src/IEncrypt.o: src/IEncrypt.cpp.o
.PHONY : src/IEncrypt.o

# target to build an object file
src/IEncrypt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/IEncrypt.cpp.o
.PHONY : src/IEncrypt.cpp.o

src/IEncrypt.i: src/IEncrypt.cpp.i
.PHONY : src/IEncrypt.i

# target to preprocess a source file
src/IEncrypt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/IEncrypt.cpp.i
.PHONY : src/IEncrypt.cpp.i

src/IEncrypt.s: src/IEncrypt.cpp.s
.PHONY : src/IEncrypt.s

# target to generate assembly for a file
src/IEncrypt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/IEncrypt.cpp.s
.PHONY : src/IEncrypt.cpp.s

src/ImageReader.o: src/ImageReader.cpp.o
.PHONY : src/ImageReader.o

# target to build an object file
src/ImageReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/ImageReader.cpp.o
.PHONY : src/ImageReader.cpp.o

src/ImageReader.i: src/ImageReader.cpp.i
.PHONY : src/ImageReader.i

# target to preprocess a source file
src/ImageReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/ImageReader.cpp.i
.PHONY : src/ImageReader.cpp.i

src/ImageReader.s: src/ImageReader.cpp.s
.PHONY : src/ImageReader.s

# target to generate assembly for a file
src/ImageReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/ImageReader.cpp.s
.PHONY : src/ImageReader.cpp.s

src/ImageWriter.o: src/ImageWriter.cpp.o
.PHONY : src/ImageWriter.o

# target to build an object file
src/ImageWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/ImageWriter.cpp.o
.PHONY : src/ImageWriter.cpp.o

src/ImageWriter.i: src/ImageWriter.cpp.i
.PHONY : src/ImageWriter.i

# target to preprocess a source file
src/ImageWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/ImageWriter.cpp.i
.PHONY : src/ImageWriter.cpp.i

src/ImageWriter.s: src/ImageWriter.cpp.s
.PHONY : src/ImageWriter.s

# target to generate assembly for a file
src/ImageWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/ImageWriter.cpp.s
.PHONY : src/ImageWriter.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CryptoGraphix.dir/build.make CMakeFiles/CryptoGraphix.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CryptoGraphix"
	@echo "... src/AES256Encryption.o"
	@echo "... src/AES256Encryption.i"
	@echo "... src/AES256Encryption.s"
	@echo "... src/IEncrypt.o"
	@echo "... src/IEncrypt.i"
	@echo "... src/IEncrypt.s"
	@echo "... src/ImageReader.o"
	@echo "... src/ImageReader.i"
	@echo "... src/ImageReader.s"
	@echo "... src/ImageWriter.o"
	@echo "... src/ImageWriter.i"
	@echo "... src/ImageWriter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

